[project]
name = "hb_knowledge_app"
authors = [
    { name = "HBOS", email = "admin@example.com" },
]
description = "HBOS controlled knowledge access and evidence delivery"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = ["jsonschema==4.26.0"]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"
hbos_portal = ">=0.0.1"
