services:
  backend:
    image: frappe/erpnext:${ERPNEXT_VERSION}
    networks:
      - frappe_network
    restart: on-failure
    volumes:
      - ./runtime/apps/hrms:/home/frappe/frappe-bench/apps/hrms
      - ./apps/hb_attendance_app:/home/frappe/frappe-bench/apps/hb_attendance_app
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: ${MARIADB_HOST}
      DB_PORT: "${DB_PORT}"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      PYTHONPATH: /home/frappe/frappe-bench/apps/hrms:/home/frappe/frappe-bench/apps/hb_attendance_app
      FEISHU_APP_ID: ${FEISHU_APP_ID}
      FEISHU_APP_SECRET: ${FEISHU_APP_SECRET}
      DELICLOUD_APP_KEY: ${DELICLOUD_APP_KEY}
      DELICLOUD_APP_SECRET: ${DELICLOUD_APP_SECRET}

  configurator:
    image: frappe/erpnext:${ERPNEXT_VERSION}
    networks:
      - frappe_network
    restart: "no"
    entrypoint:
      - bash
      - -c
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: ${MARIADB_HOST}
      DB_PORT: "${DB_PORT}"
      REDIS_CACHE: ${REDIS_CACHE}
      REDIS_QUEUE: ${REDIS_QUEUE}
      SOCKETIO_PORT: "${SOCKETIO_PORT}"
      PYTHONPATH: /home/frappe/frappe-bench/apps/hrms:/home/frappe/frappe-bench/apps/hb_attendance_app
    volumes:
      - ./runtime/apps/hrms:/home/frappe/frappe-bench/apps/hrms
      - ./apps/hb_attendance_app:/home/frappe/frappe-bench/apps/hb_attendance_app
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  create-site:
    image: frappe/erpnext:${ERPNEXT_VERSION}
    networks:
      - frappe_network
    restart: "no"
    depends_on:
      - db
      - redis-cache
      - redis-queue
      - configurator
    volumes:
      - ./runtime/apps/hrms:/home/frappe/frappe-bench/apps/hrms
      - ./apps/hb_attendance_app:/home/frappe/frappe-bench/apps/hb_attendance_app
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    entrypoint:
      - bash
      - -c
    command:
      - >
        wait-for-it -t 120 $$DB_HOST:$$DB_PORT;
        wait-for-it -t 120 redis-cache:6379;
        wait-for-it -t 120 redis-queue:6379;
        export start=`date +%s`;
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep 5;
          if (( `date +%s`-start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1;
          fi;
        done;
        echo "sites/common_site_config.json found";
        bench new-site $$SITE_NAME \
          --mariadb-user-host-login-scope='%' \
          --admin-password=$$ADMIN_PASSWORD \
          --db-root-username=root \
          --db-root-password=$$DB_ROOT_PASSWORD \
          --install-app erpnext \
          --set-default;
    environment:
      SITE_NAME: ${SITE_NAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_HOST: ${MARIADB_HOST}
      DB_PORT: "${DB_PORT}"
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      PYTHONPATH: /home/frappe/frappe-bench/apps/hrms:/home/frappe/frappe-bench/apps/hb_attendance_app

  db:
    image: mariadb:11.8
    networks:
      - frappe_network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    image: frappe/erpnext:${ERPNEXT_VERSION}
    networks:
      - frappe_network
    depends_on:
      - websocket
    restart: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: ${FRAPPE_SITE_NAME_HEADER}
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS}
      UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER}
      UPSTREAM_REAL_IP_RECURSIVE: "${UPSTREAM_REAL_IP_RECURSIVE}"
      PROXY_READ_TIMEOUT: "${PROXY_READ_TIMEOUT}"
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE}
    volumes:
      - ./runtime/apps/hrms:/home/frappe/frappe-bench/apps/hrms
      - ./apps/hb_attendance_app:/home/frappe/frappe-bench/apps/hb_attendance_app
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    ports:
      - "${HTTP_PORT}:8080"

  queue-long:
    image: frappe/erpnext:${ERPNEXT_VERSION}
    networks:
      - frappe_network
    restart: on-failure
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    volumes:
      - ./runtime/apps/hrms:/home/frappe/frappe-bench/apps/hrms
      - ./apps/hb_attendance_app:/home/frappe/frappe-bench/apps/hb_attendance_app
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      FRAPPE_REDIS_CACHE: redis://${REDIS_CACHE}
      FRAPPE_REDIS_QUEUE: redis://${REDIS_QUEUE}
      PYTHONPATH: /home/frappe/frappe-bench/apps/hrms:/home/frappe/frappe-bench/apps/hb_attendance_app

  queue-short:
    image: frappe/erpnext:${ERPNEXT_VERSION}
    networks:
      - frappe_network
    restart: on-failure
    command:
      - bench
      - worker
      - --queue
      - short,default
    volumes:
      - ./runtime/apps/hrms:/home/frappe/frappe-bench/apps/hrms
      - ./apps/hb_attendance_app:/home/frappe/frappe-bench/apps/hb_attendance_app
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      FRAPPE_REDIS_CACHE: redis://${REDIS_CACHE}
      FRAPPE_REDIS_QUEUE: redis://${REDIS_QUEUE}
      PYTHONPATH: /home/frappe/frappe-bench/apps/hrms:/home/frappe/frappe-bench/apps/hb_attendance_app

  redis-queue:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    restart: on-failure
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    restart: on-failure

  scheduler:
    image: frappe/erpnext:${ERPNEXT_VERSION}
    networks:
      - frappe_network
    restart: on-failure
    command:
      - bench
      - schedule
    environment:
      PYTHONPATH: /home/frappe/frappe-bench/apps/hrms:/home/frappe/frappe-bench/apps/hb_attendance_app
      FEISHU_APP_ID: ${FEISHU_APP_ID}
      FEISHU_APP_SECRET: ${FEISHU_APP_SECRET}
      DELICLOUD_APP_KEY: ${DELICLOUD_APP_KEY}
      DELICLOUD_APP_SECRET: ${DELICLOUD_APP_SECRET}
    volumes:
      - ./runtime/apps/hrms:/home/frappe/frappe-bench/apps/hrms
      - ./apps/hb_attendance_app:/home/frappe/frappe-bench/apps/hb_attendance_app
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  websocket:
    image: frappe/erpnext:${ERPNEXT_VERSION}
    networks:
      - frappe_network
    restart: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    environment:
      FRAPPE_REDIS_CACHE: redis://${REDIS_CACHE}
      FRAPPE_REDIS_QUEUE: redis://${REDIS_QUEUE}
    volumes:
      - ./runtime/apps/hrms:/home/frappe/frappe-bench/apps/hrms
      - ./apps/hb_attendance_app:/home/frappe/frappe-bench/apps/hb_attendance_app
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

volumes:
  db-data:
  redis-queue-data:
  sites:
  logs:

networks:
  frappe_network:
    driver: bridge
