<template>
  <section class="process-panel" aria-label="生产原理演示控制">
    <div class="process-title"><div><span class="eyebrow">{{ session.equipmentId }} · 生产主线</span><h3>{{ current.label }}</h3></div><span class="demo-badge">原理演示 / 非现场状态 / 非操作规程</span></div>
    <div class="steps" aria-label="跳转示教步骤"><button v-for="(step,i) in steps" :key="step.label" :aria-current="i === index ? 'step' : undefined" @click="$emit('seek', i * 12)"><span>{{ String(i+1).padStart(2,'0') }}</span>{{ step.label }}</button></div>
    <p class="step-note">{{ current.note }}<span v-if="index===2">当前：{{ wash.label }}</span></p>
    <div class="playback"><button class="play" :aria-label="session.paused ? '播放生产演示' : '暂停生产演示'" @click="$emit('toggle')">{{ session.paused ? '▶ 播放' : 'Ⅱ 暂停' }}</button><button class="replay" aria-label="重播生产演示" @click="$emit('replay')">↻ 重播</button><label class="timeline">演示进度<input type="range" min="0" max="60" step="0.1" :value="session.time" @input="$emit('seek', Number(($event.target as HTMLInputElement).value))" /></label><output>{{ session.time.toFixed(1) }} / 60s</output><label class="speed">速度<select :value="session.speed" @change="$emit('speed', Number(($event.target as HTMLSelectElement).value))"><option :value="0.5">0.5×</option><option :value="1">1×</option><option :value="2">2×</option></select></label></div>
    <div class="process-footer"><label><input type="checkbox" :checked="session.followCamera" @change="$emit('follow', ($event.target as HTMLInputElement).checked)" /> 跟随示教镜头</label><span>手动操作立即接管镜头；时长仅为讲解节奏。</span><button @click="$emit('exit')">退出示教</button></div>
  </section>
</template>
<script setup lang="ts">
import { computed } from 'vue'
import type { DemoSession } from '@/types/twin'
import { washState } from './process/process-hardware'
const props=defineProps<{session:DemoSession}>()
defineEmits<{seek:[time:number];toggle:[];replay:[];speed:[value:number];follow:[value:boolean];exit:[]}>()
const steps=[{label:'进料',note:'观察进料路径与罐内物料的示意变化；接口与流路仍须工程核验。'},{label:'过滤',note:'液相通过简化过滤面，固相逐步截留；视觉量没有实测单位。'},{label:'洗涤',note:'按六个讲解步骤观察进入、升降、混合和排液。'},{label:'干燥',note:'观察供热、搅拌与气体移出的原理表达；没有真实温压或合格判定。'},{label:'出料',note:'观察堵头回缩与搅拌辅助出料的示意；内部形状和行程仍待核。'}]
const index=computed(()=>Math.min(4,Math.floor(props.session.time/12)))
const current=computed(()=>steps[index.value]!)
const wash=computed(()=>washState(Math.max(0,Math.min(1,(props.session.time-24)/12))))
</script>
<style scoped>
.process-panel{background:#fffdf9;border:1px solid #e4e0d8;border-radius:18px;padding:20px;display:grid;gap:16px}.process-title{display:flex;justify-content:space-between;align-items:center;gap:12px}.eyebrow{color:#8e7a54;font-size:11px;letter-spacing:.5px}.process-title h3{font-size:21px;margin:4px 0 0;color:#31445a}.demo-badge{color:#896c38;background:#f5eddd;border-radius:7px;padding:7px 9px;font-size:11px}.steps{display:grid;grid-template-columns:repeat(5,1fr);gap:7px}.steps button{display:flex;align-items:center;gap:8px;border:1px solid #e4e1db;background:white;border-radius:9px;padding:10px;color:#78808b;font-size:13px;cursor:pointer}.steps button[aria-current=step]{background:#5e5b94;color:white;border-color:#5e5b94}.steps span{font-size:11px;opacity:.65}.step-note{font-size:13px;line-height:1.7;color:#687386;margin:0}.step-note span{display:block;color:#76623d}.playback{display:flex;gap:10px;align-items:center}.playback button{border:1px solid #dddde5;border-radius:9px;min-height:40px;padding:0 14px;background:white;cursor:pointer}.playback button.play{background:#615b9e;color:white;border:0}.timeline{flex:1;font-size:0}.timeline input{width:100%;accent-color:#615b9e;min-height:36px}.playback output{font-variant-numeric:tabular-nums;font-size:12px;color:#768092;white-space:nowrap}.speed{display:flex;align-items:center;gap:5px;font-size:12px;color:#798192}.speed select{min-height:36px;border:1px solid #dddde5;border-radius:7px;padding:0 6px;background:white}.process-footer{border-top:1px solid #eeebe5;padding-top:13px;display:flex;gap:16px;align-items:center;font-size:12px;color:#8a8e99}.process-footer label{white-space:nowrap;color:#5e6576}.process-footer input{accent-color:#615b9e}.process-footer button{margin-left:auto;color:#74677d;border:0;background:none;min-height:34px;cursor:pointer}.process-panel button:focus-visible,.process-panel input:focus-visible,.process-panel select:focus-visible{outline:3px solid #655cf0;outline-offset:2px}@media(max-width:700px){.process-panel{padding:15px}.process-title{align-items:flex-start;flex-direction:column}.steps{gap:4px}.steps button{padding:10px 4px;gap:4px;font-size:12px}.steps span{display:none}.playback{flex-wrap:wrap}.timeline{order:5;flex-basis:100%}.process-footer{flex-wrap:wrap}.process-footer>span{width:100%;order:3}}
</style>
