<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { RouterLink } from 'vue-router'
import { getKnowledgeStatus } from '@/services/p1Api'
import { getMaintenance, maintenanceAction, previewImport, uploadKnowledge, type ImportItem, type MaintenanceDashboard, type QualityPreview, type MaintenanceFeedback, type VersionTarget } from '@/services/knowledgeMaintenanceApi'
const allowed=ref(false), initialized=ref(false), busy=ref(false), error=ref(''), notice=ref('')
const data=ref<MaintenanceDashboard|null>(null), department=ref('production'), selectedBatch=ref(''), page=ref(1)
const file=ref<File|null>(null), sharing=ref(false), replacement=ref<VersionTarget|null>(null)
const qualityOpen=ref(false), preview=ref<QualityPreview|null>(null), qualityItem=ref<ImportItem|null>(null), checks=ref<string[]>([]), qualityNote=ref(''), operationReason=ref('')
const feedbackReplies=ref<Record<string,string>>({})
let epoch=0, readSequence=0
const batch=computed(()=>data.value?.selected)
const canParse=computed(()=>data.value?.import_availability.can_parse===true)
const replacements=computed(()=>data.value?.published_documents?.filter(i=>i.department===department.value)||[])
watch(department,()=>{replacement.value=null})
const parseNames:Record<string,string>={'planned':'待解析','uploaded':'待解析','parse_intent':'请求待核验','parse_queued':'解析中','parsed/indexed':'解析完成','parse_failed':'解析失败','quarantined':'身份待核对','skipped_duplicate':'重复，保留原版本'}
const relationships:Record<string,string>={NEW:'新增资料',UPDATE_CONFIRMED:'已确认换版',SAME_CONTENT_SKIP:'相同内容，保留原身份',UPDATE_CANDIDATE:'换版关系待确认',CONFLICT:'身份冲突'}
function message(error:unknown){return error instanceof Error?error.message:'维护服务暂不可用。'}
async function refresh(){const current=epoch,seq=++readSequence;try{const result=await getMaintenance(selectedBatch.value||undefined,page.value);if(current!==epoch||seq!==readSequence)return;data.value=result}catch(e){if(current===epoch&&seq===readSequence)error.value=message(e)}}
async function act(work:()=>Promise<unknown>,success:string){if(busy.value)return;const current=epoch;busy.value=true;error.value='';notice.value='';try{await work();if(current!==epoch)return;notice.value=success;await refresh()}catch(e){if(current===epoch)error.value=message(e)}finally{if(current===epoch)busy.value=false}}
function chooseFile(event:Event){file.value=(event.target as HTMLInputElement).files?.[0]||null;notice.value=''}
async function upload(){if(!file.value||!sharing.value)return;await act(async()=>{const result=await uploadKnowledge(file.value!,department.value,sharing.value,replacement.value||undefined);selectedBatch.value=result.batch_id;page.value=1;file.value=null;sharing.value=false;replacement.value=null},'上传已保存。请查看去重关系后发起解析；解析、质量和发布分别完成。')}
function changeBatch(){if(busy.value)return;page.value=1;replacement.value=null;epoch++;void refresh()}
function args(item:ImportItem){return {batch_id:selectedBatch.value,document_id:item.document_id}}
async function openQuality(item:ImportItem){qualityOpen.value=true;qualityItem.value=item;preview.value=null;checks.value=[];qualityNote.value='';const current=++epoch;try{const result=await previewImport(selectedBatch.value,item.document_id);if(current===epoch&&qualityOpen.value)preview.value=result}catch(e){if(current===epoch)error.value=message(e)}}
function closeQuality(){if(busy.value)return;qualityOpen.value=false;preview.value=null;qualityItem.value=null;epoch++}
async function confirmQuality(){const item=qualityItem.value;if(!item||checks.value.length!==4||qualityNote.value.trim().length<3)return;await act(()=>maintenanceAction('review_import',{...args(item),checks:checks.value,note:qualityNote.value.trim()}),'本版本质量核对已保存。发布仍需单独操作。');if(!error.value)closeQuality()}
async function publish(item:ImportItem){const operation=item.publication_status==='Withdrawn'?'restore':item.current_version&&item.current_version!==item.version_id?'replace':'publish';if(operation!=='publish'&&operationReason.value.trim().length<3){error.value='换版或恢复前请填写至少三个字的操作原因。';return}await act(()=>maintenanceAction('publish_import',{batch_id:selectedBatch.value,document_ids:[item.document_id],operation,expected_version:item.current_version,reason:operationReason.value.trim()||undefined}),'发布状态已更新。目录与来源将按当前版本重新校验。')}
async function withdraw(item:ImportItem){if(operationReason.value.trim().length<3){error.value='下架前请填写至少三个字的操作原因。';return}await act(()=>maintenanceAction('withdraw_import',{...args(item),expected_version:item.current_version,reason:operationReason.value.trim()}),'资料已下架。原历史和收藏仍保留，失效来源不能继续展示。')}
async function reviewFeedback(item:MaintenanceFeedback,status:string){await act(()=>maintenanceAction('review_feedback',{activity_id:item.id,status,reply:feedbackReplies.value[item.id]||''}),'反馈处理已保存，提交人可查看状态和回复。')}
onMounted(async()=>{const current=epoch;try{const status=await getKnowledgeStatus();if(current!==epoch)return;allowed.value=Boolean(status.can_maintain);if(allowed.value)await refresh()}catch(e){error.value=message(e)}finally{if(current===epoch)initialized.value=true}})
onBeforeUnmount(()=>{epoch++;readSequence++})
</script>
<template>
 <main class="maintenance-page">
  <header class="maintenance-heading"><div><p class="eyebrow">HBOS · 知识维护</p><h1>把资料变成可用知识</h1><p>选择部门，保存资料，核对解析质量，再发布给普通阅读者。</p></div><RouterLink to="/hbos/knowledge">返回知识库</RouterLink></header>
  <a-alert v-if="error" type="error" :message="error" show-icon class="message" />
  <a-alert v-if="notice" type="success" :message="notice" show-icon class="message" />
  <a-spin v-if="!initialized" />
  <a-result v-else-if="!allowed" status="403" title="当前账号没有知识维护权限" sub-title="请使用分配的维护账号登录。普通阅读者可从知识库查看已发布资料。" />
  <template v-else>
   <a-alert v-if="!canParse" type="warning" message="解析暂停：原预算存在未结算请求。可以继续上传、核对已有结果、发布、下架和处理反馈。" show-icon class="message" />
   <section class="maintenance-panel hbos-glass-g3"><div class="section-heading"><h2>增加资料</h2><span>私有暂存 · 单文件最多 20 MB</span></div>
    <p class="help">支持 DOC、DOCX、可提取文本 PDF，以及有实际需求的 XLSX、PPTX、UTF-8 文本。宏、嵌入对象、外部关系及压缩包不进入普通上传。扫描件质量不足时保留为待人工处理。</p>
    <div class="upload-grid"><label>所属部门<a-select v-model:value="department" :options="data?.departments.map(d=>({value:d.key,label:d.title}))" /></label><label>资料文件<input type="file" accept=".doc,.docx,.pdf,.xlsx,.pptx,.txt,.md" @change="chooseFile" /></label><label>版本关系<a-select show-search :filter-option="(input:string,option:any)=>String(option.label).toLowerCase().includes(input.toLowerCase())" :value="replacement?.document_id||''" :options="[{value:'',label:'新增或自动识别同内容'},...replacements.map(i=>({value:i.document_id,label:'替换：'+i.title}))]" @change="(value:string)=>replacement=replacements.find(i=>i.document_id===value)||null" /></label></div>
    <a-checkbox v-model:checked="sharing">我确认该资料已获准作为本部门内部参考共享；隔离或敏感材料不能借此自动准入。</a-checkbox>
    <div class="upload-footer"><span class="filename">{{ file?.name||'请选择需要新增的获准资料。' }}</span><a-button type="primary" :loading="busy" :disabled="!file||!sharing" @click="upload">保存资料并查看去重</a-button></div>
   </section>
   <section class="maintenance-panel hbos-glass-g3"><div class="section-heading"><h2>批次与当前版本</h2><a-button :disabled="busy" @click="refresh">刷新进度</a-button></div>
    <a-select v-model:value="selectedBatch" :disabled="busy" class="batch-select" placeholder="选择资料批次" :options="data?.batches.map(b=>({value:b.name,label:b.label}))" @change="changeBatch" />
    <template v-if="batch"><p class="help">共 {{ batch.total }} 项；解析完成 {{ batch.counts.parsed }}，失败 {{ batch.counts.failed }}，质量通过 {{ batch.counts.quality_passed }}。解析完成后仍需核对和发布。</p><a-alert v-if="batch.last_error" type="warning" message="本次处理已保存检查点，请核对失败项或预算状态后再操作。" />
     <label class="reason-label">换版、下架或恢复原因<a-input v-model:value="operationReason" :maxlength="500" placeholder="填写这次操作的原因" /></label>
     <div class="import-grid"><article v-for="item in batch.items" :key="item.version_id+item.filename" class="import-card"><h3>{{ item.title }}</h3><p class="filename">{{ item.filename }}</p><a-tag>{{ relationships[item.relationship]||item.relationship }}</a-tag><p>{{ parseNames[item.parse_status]||item.parse_status }} · {{ item.chunk_count }} 个片段</p><a-progress v-if="item.parse_status==='parse_queued'" :percent="Math.round(item.progress*100)" size="small" /><p>质量：{{ item.relationship==='SAME_CONTENT_SKIP'?'沿用原版本记录':item.quality_status==='Passed'?'已核对':'待核对' }} · {{ item.publication_status==='Published'?'已发布':item.publication_status==='Withdrawn'?'已下架':'未发布' }}</p><p v-if="item.quality_note" class="help">{{ item.quality_note }}</p>
      <a-space wrap><a-button v-if="['planned','uploaded'].includes(item.parse_status)&&item.relationship!=='SAME_CONTENT_SKIP'" :disabled="busy||!canParse" @click="act(()=>maintenanceAction('queue_import',{batch_id:selectedBatch,document_ids:[item.document_id],operation:'parse'}),'解析已排队，请刷新查看进度。')">解析</a-button><a-button v-if="item.parse_status==='parse_failed'" :disabled="busy||!canParse" @click="act(()=>maintenanceAction('queue_import',{batch_id:selectedBatch,document_ids:[item.document_id],operation:'retry'}),'失败重试已排队。')">重试失败项</a-button><a-button v-if="item.parse_status==='parsed/indexed'" :disabled="busy" @click="openQuality(item)">核对质量</a-button><a-button v-if="item.parse_status==='parsed/indexed'&&item.quality_status==='Passed'&&item.publication_status!=='Published'" type="primary" :disabled="busy" @click="publish(item)">{{ item.publication_status==='Withdrawn'?'恢复发布':item.current_version&&item.current_version!==item.version_id?'确认换版':'发布' }}</a-button><a-popconfirm v-if="item.publication_status==='Published'" title="下架后员工不能展开该版本的来源。确认下架？" ok-text="确认下架" cancel-text="取消" @confirm="withdraw(item)"><a-button danger :disabled="busy">下架</a-button></a-popconfirm></a-space>
     </article></div><a-pagination v-model:current="page" :total="batch.total" :page-size="12" :show-size-changer="false" :simple="false" @change="refresh" />
    </template><a-empty v-else description="选择批次，查看去重、解析、质量及发布状态。" />
   </section>
   <section class="maintenance-panel hbos-glass-g3"><div class="section-heading"><h2>员工反馈</h2><span>处理结果仅向提交人和维护人展示</span></div><a-empty v-if="!data?.feedback.items.length" description="暂无反馈" /><article v-for="item in data?.feedback.items" :key="item.id" class="feedback-card"><a-tag>{{ item.category }}</a-tag><a-tag>{{ item.status==='Resolved'?'已处理':item.status==='In Review'?'处理中':'待处理' }}</a-tag><p>{{ item.note }}</p><a-textarea v-model:value="feedbackReplies[item.id]" :maxlength="500" placeholder="填写给提交人的回复" :auto-size="{minRows:2,maxRows:5}" /><a-space wrap><a-button :disabled="busy" @click="reviewFeedback(item,'In Review')">标记处理中</a-button><a-button type="primary" :disabled="busy" @click="reviewFeedback(item,'Resolved')">保存处理结果</a-button></a-space></article></section>
  </template>
  <a-drawer :open="qualityOpen" title="核对本版本质量" width="min(700px, 100vw)" :content-wrapper-style="{maxWidth:'100vw'}" placement="right" :mask-closable="!busy" :closable="!busy" @close="closeQuality"><template v-if="preview"><h2>{{ preview.title }}</h2><p class="help">以下是有限解析摘录。关键数字、单位、否定语和表格关系须与获准原资料核对；片段顺序不能当作原页码。</p><blockquote v-for="(fragment,index) in preview.fragments" :key="index" class="quality-fragment">{{ fragment.text }}<small>{{ fragment.location }}</small></blockquote><a-checkbox-group v-model:value="checks" class="checks"><a-checkbox value="text">正文与否定语</a-checkbox><a-checkbox value="numbers">数字、单位和条件</a-checkbox><a-checkbox value="tables">表格与条款关系</a-checkbox><a-checkbox value="identity">文件和版本身份</a-checkbox></a-checkbox-group><a-textarea v-model:value="qualityNote" :maxlength="500" :auto-size="{minRows:3,maxRows:7}" placeholder="记录核对结果、限制或原件页码" /><a-button type="primary" :disabled="checks.length!==4||qualityNote.trim().length<3" :loading="busy" @click="confirmQuality">保存质量核对</a-button></template><a-spin v-else /></a-drawer>
 </main>
</template>
<style scoped>
.maintenance-page{width:100%;max-width:1440px;margin:0 auto;padding:28px 32px 48px;box-sizing:border-box;min-width:0;color:var(--hbos-text-primary)}.maintenance-heading,.section-heading,.upload-footer{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}.maintenance-heading{margin-bottom:24px}.eyebrow{font-size:12px;letter-spacing:.08em;color:var(--hbos-text-secondary)}h1{font-size:30px;line-height:1.3;margin:8px 0 12px;font-weight:600}h2{font-size:20px;margin:0;font-weight:600}h3{font-size:16px;line-height:1.5;margin:0 0 8px;font-weight:600;overflow-wrap:anywhere}.message{margin:0 0 16px}.maintenance-panel{border:1px solid var(--hbos-border-strong);border-radius:var(--hbos-radius-panel);background:var(--hbos-bg-surface);padding:24px;margin-bottom:20px;min-width:0}.help,.filename{font-size:14px;line-height:1.7;color:var(--hbos-text-secondary);overflow-wrap:anywhere}.upload-grid{display:grid;grid-template-columns:160px minmax(0,1fr) minmax(200px,1fr);gap:16px;margin:20px 0}.upload-grid label,.reason-label{display:flex;flex-direction:column;gap:8px;min-width:0}.upload-grid :deep(.ant-select){width:100%}input[type=file]{max-width:100%;font-size:14px}.upload-footer{margin-top:16px}.batch-select{width:100%;margin:20px 0 4px}.reason-label{margin:16px 0}.import-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;margin:20px 0}.import-card{border:1px solid var(--hbos-border-strong);border-radius:var(--hbos-radius-card);padding:18px;min-width:0}.feedback-card{border-top:1px solid var(--hbos-border-strong);padding:20px 0;overflow-wrap:anywhere}.feedback-card :deep(.ant-space){margin-top:12px}.quality-fragment{border-left:3px solid var(--hbos-brand-blue);padding:12px 16px;margin:16px 0;white-space:pre-wrap;overflow-wrap:anywhere;font-size:14px;line-height:1.8;background:#f7f9fc}.quality-fragment small{display:block;color:#667085;margin-top:8px}.checks{display:flex;flex-direction:column;gap:12px;margin:20px 0}.checks+.ant-input{margin-bottom:16px}@media(max-width:1024px){.import-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.upload-grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.maintenance-page{padding:20px 16px 32px}h1{font-size:26px}.maintenance-panel{padding:18px 16px}.upload-grid,.import-grid{grid-template-columns:1fr}.section-heading span{font-size:12px}.upload-footer{align-items:flex-start}.upload-footer .ant-btn{width:100%}}
</style>
