<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { PlusOutlined, FileTextOutlined, UploadOutlined, ArrowRightOutlined, MessageOutlined, HistoryOutlined } from '@ant-design/icons-vue'
import { DomainApiError, getKnowledgeStatus } from '@/services/p1Api'
import { getMaintenance, getMaintenanceFeedbackPage, maintenanceAction, previewImport, uploadKnowledge, type ImportItem, type MaintenanceDashboard, type QualityPreview, type MaintenanceFeedback, type VersionTarget } from '@/services/knowledgeMaintenanceApi'
const route=useRoute(),router=useRouter()
const props=defineProps<{sessionRevision?:number}>()
const view=computed(()=>route.path.endsWith('/upload')?'upload':route.path.endsWith('/versions')?'versions':route.path.endsWith('/feedback')?'feedback':'manage')
const titles={manage:'资料管理',upload:'新增资料',versions:'版本管理',feedback:'员工反馈'}
const allowed=ref(false),initialized=ref(false),busy=ref(false),error=ref(''),notice=ref(''),loading=ref(false)
const data=ref<MaintenanceDashboard|null>(null),department=ref('production'),selectedBatch=ref(''),page=ref(1),filter=ref(''),departmentFilter=ref(''),listPage=ref(1)
const file=ref<File|null>(null),sharing=ref(false),replacement=ref<VersionTarget|null>(null),uploadStage=ref(0)
const qualityOpen=ref(false),preview=ref<QualityPreview|null>(null),qualityItem=ref<ImportItem|null>(null),checks=ref<string[]>([]),qualityNote=ref(''),operationReason=ref('')
const detailOpen=ref(false),detail=ref<ImportItem|null>(null),detailLoading=ref(false),detailTitle=ref('')
const feedbackOpen=ref(false),selectedFeedback=ref<MaintenanceFeedback|null>(null),reply=ref(''),feedbackItems=ref<MaintenanceFeedback[]>([]),feedbackPage=ref(1),feedbackHasMore=ref(false),feedbackStatus=ref(''),feedbackQuery=ref('')
let epoch=0,readSequence=0,feedbackSequence=0
const batch=computed(()=>data.value?.selected)
const canParse=computed(()=>data.value?.import_availability.can_parse===true)
const replacements=computed(()=>data.value?.published_documents.filter(i=>i.department===department.value)||[])
const parseNames:Record<string,string>={'planned':'待解析','uploaded':'待解析','parse_intent':'请求待核验','parse_queued':'解析中','parsed/indexed':'解析完成','parse_failed':'解析失败','quarantined':'身份待核对','skipped_duplicate':'重复，保留原版本'}
const relationships:Record<string,string>={NEW:'新增资料',UPDATE_CONFIRMED:'已确认换版',SAME_CONTENT_SKIP:'相同内容，保留原身份',UPDATE_CANDIDATE:'换版关系待确认',CONFLICT:'身份冲突'}
const departmentName=(key:string)=>data.value?.departments.find(d=>d.key===key)?.title||key
const managed=computed(()=>{
  const docs=(data.value?.published_documents||[]).map(d=>({...d,status:'已发布',item:undefined as ImportItem|undefined}))
  for(const item of batch.value?.items||[])if(!docs.some(d=>d.version_id===item.version_id))docs.unshift({document_id:item.document_id,title:item.title,version_id:item.version_id,current_version:item.current_version||'',department:batch.value?.department||'',status:item.publication_status==='Withdrawn'?'已下架':parseNames[item.parse_status]||'待核对',item})
  return docs.filter(d=>(!filter.value||(d.title).toLowerCase().includes(filter.value.trim().toLowerCase()))&&(!departmentFilter.value||d.department===departmentFilter.value))
})
const visibleDocs=computed(()=>managed.value.slice((listPage.value-1)*4,listPage.value*4))
watch([filter,departmentFilter],()=>{listPage.value=1})
watch(department,()=>{replacement.value=null})
watch(view,()=>{error.value='';notice.value='';detailOpen.value=false;feedbackOpen.value=false;if(view.value==='feedback')void refreshFeedback()})
function message(e:unknown){return e instanceof Error?e.message:'维护服务暂不可用。'}
function failure(e:unknown){error.value=message(e);if(e instanceof DomainApiError&&['SCOPE_REJECTED','FORBIDDEN','AUTHENTICATION_REQUIRED','CLIENT_AUTH_FAILED'].includes(e.code)){epoch++;data.value=null;preview.value=null;detail.value=null;feedbackItems.value=[];allowed.value=false;qualityOpen.value=false;detailOpen.value=false;feedbackOpen.value=false}}
async function refresh(){const current=epoch,seq=++readSequence;loading.value=true;error.value='';try{let result=await getMaintenance(selectedBatch.value||undefined,page.value);if(current!==epoch||seq!==readSequence)return;if(!selectedBatch.value&&result.batches.length){selectedBatch.value=result.batches[0]!.name;result=await getMaintenance(selectedBatch.value,1)}if(current===epoch&&seq===readSequence)data.value=result}catch(e){if(current===epoch&&seq===readSequence)failure(e)}finally{if(current===epoch&&seq===readSequence)loading.value=false}}
async function refreshFeedback(){const current=epoch,seq=++feedbackSequence;loading.value=true;try{if(feedbackQuery.value.trim()){
 const all:MaintenanceFeedback[]=[]
 for(let n=1;n<=100;n++){const result=await getMaintenanceFeedbackPage(n,feedbackStatus.value);if(current!==epoch||seq!==feedbackSequence)return;all.push(...result.items);if(!result.has_more)break;if(n===100)throw new DomainApiError('SERVICE_ERROR','反馈过多，请缩小状态范围。')}
 const query=feedbackQuery.value.trim().toLowerCase(),filtered=all.filter(item=>(item.note+' '+item.category).toLowerCase().includes(query))
 if(current===epoch&&seq===feedbackSequence){feedbackItems.value=filtered.slice((feedbackPage.value-1)*6,feedbackPage.value*6);feedbackHasMore.value=feedbackPage.value*6<filtered.length}
 }else{const result=await getMaintenanceFeedbackPage(feedbackPage.value,feedbackStatus.value);if(current===epoch&&seq===feedbackSequence){feedbackItems.value=result.items;feedbackHasMore.value=result.has_more}}}catch(e){if(current===epoch&&seq===feedbackSequence)failure(e)}finally{if(current===epoch&&seq===feedbackSequence)loading.value=false}}
watch(feedbackPage,refreshFeedback);watch(feedbackQuery,()=>{feedbackPage.value=1;void refreshFeedback()});watch(feedbackStatus,()=>{feedbackPage.value=1;void refreshFeedback()})
async function act(work:()=>Promise<unknown>,success:string){if(busy.value)return;const current=epoch;busy.value=true;error.value='';notice.value='';try{await work();if(current!==epoch)return;notice.value=success;await refresh();if(detail.value){const item=batch.value?.items.find(i=>i.version_id===detail.value?.version_id);if(item)detail.value=item}}catch(e){if(current===epoch)failure(e)}finally{if(current===epoch)busy.value=false}}
function chooseFile(event:Event){file.value=(event.target as HTMLInputElement).files?.[0]||null;notice.value=''}
async function upload(){if(!file.value||!sharing.value)return;await act(async()=>{const result=await uploadKnowledge(file.value!,department.value,sharing.value,replacement.value||undefined);selectedBatch.value=result.batch_id;data.value=null;page.value=1;file.value=null;sharing.value=false;replacement.value=null;uploadStage.value=1},'上传已保存，请核对重复与版本关系后开始解析。')}
function changeBatch(){if(busy.value)return;page.value=1;detailOpen.value=false;epoch++;void refresh()}
function args(item:ImportItem){return {batch_id:selectedBatch.value,document_id:item.document_id}}
async function openQuality(item:ImportItem){qualityOpen.value=true;qualityItem.value=item;preview.value=null;checks.value=[];qualityNote.value='';const current=epoch;try{const result=await previewImport(selectedBatch.value,item.document_id);if(current===epoch&&qualityOpen.value&&qualityItem.value?.version_id===item.version_id)preview.value=result}catch(e){if(current===epoch)failure(e)}}
function closeQuality(){if(busy.value)return;qualityOpen.value=false;preview.value=null;qualityItem.value=null}
async function confirmQuality(){const item=qualityItem.value;if(!item||checks.value.length!==4||qualityNote.value.trim().length<3)return;await act(()=>maintenanceAction('review_import',{...args(item),checks:checks.value,note:qualityNote.value.trim()}),'本版本质量核对已保存，发布需要单独确认。');if(!error.value){closeQuality();uploadStage.value=2}}
async function publish(item:ImportItem){const operation=item.publication_status==='Withdrawn'?'restore':item.current_version&&item.current_version!==item.version_id?'replace':'publish';if(operation!=='publish'&&operationReason.value.trim().length<3){error.value='换版或恢复前请填写至少三个字的操作原因。';return}await act(()=>maintenanceAction('publish_import',{batch_id:selectedBatch.value,document_ids:[item.document_id],operation,expected_version:item.current_version,reason:operationReason.value.trim()||undefined}),'发布状态已更新，员工可按当前授权版本查询。')}
async function withdraw(item:ImportItem){if(operationReason.value.trim().length<3){error.value='下架前请填写至少三个字的操作原因。';return}await act(()=>maintenanceAction('withdraw_import',{...args(item),expected_version:item.current_version,reason:operationReason.value.trim()}),'资料已下架，旧来源与收藏将立即重新核验。')}
async function queue(item:ImportItem){await act(()=>maintenanceAction('queue_import',{batch_id:selectedBatch.value,document_ids:[item.document_id],operation:item.parse_status==='parse_failed'?'retry':'parse'}),'解析已排队，请刷新查看实际处理进度。')}
async function openDetails(doc:{title:string;document_id:string;version_id?:string;item?:ImportItem}){
 detailOpen.value=true;detail.value=null;detailTitle.value=doc.title;detailLoading.value=true;operationReason.value='';const current=epoch
 try{
  if(doc.item){detail.value=doc.item;return}
  for(const candidate of data.value?.batches||[]){
   let n=1
   while(true){const result=await getMaintenance(candidate.name,n);if(current!==epoch||!detailOpen.value)return;const item=result.selected?.items.find(i=>i.document_id===doc.document_id&&(!doc.version_id||i.version_id===doc.version_id)&&i.relationship!=='SAME_CONTENT_SKIP');if(item){selectedBatch.value=candidate.name;page.value=n;data.value=result;detail.value=item;return}if(!result.selected||n*result.selected.page_size>=result.selected.total)break;n++}
  }
 }catch(e){if(current===epoch)failure(e)}finally{if(current===epoch)detailLoading.value=false}
}
async function newRevision(){const target=data.value?.published_documents.find(d=>d.document_id===detail.value?.document_id);if(!target)return;department.value=target.department;await nextTick();replacement.value=target;uploadStage.value=0;detailOpen.value=false;await router.push('/hbos/knowledge/maintenance/upload')}
function openFeedback(item:MaintenanceFeedback){selectedFeedback.value=item;reply.value=item.maintenance_reply||item.reply||'';feedbackOpen.value=true}
async function reviewFeedback(status:string){const item=selectedFeedback.value;if(!item)return;await act(()=>maintenanceAction('review_feedback',{activity_id:item.id,status,reply:reply.value}),'反馈处理已保存，提交人可查看状态和回复。');if(!error.value){feedbackOpen.value=false;await refreshFeedback()}}
async function revalidate(){const current=epoch;try{const status=await getKnowledgeStatus();if(current!==epoch)return;allowed.value=Boolean(status.can_maintain);if(!allowed.value){failure(new DomainApiError('FORBIDDEN','当前账号没有知识维护权限。'));return}await refresh();if(view.value==='feedback')await refreshFeedback()}catch(e){failure(e)}finally{if(current===epoch)initialized.value=true}}
watch(()=>props.sessionRevision,()=>{void revalidate()})
onMounted(revalidate)
onBeforeUnmount(()=>{epoch++;readSequence++;feedbackSequence++})
</script>
<template>
 <div class="maintenance-page">
  <header class="kb-heading"><div><h1>{{titles[view]}}</h1><p>上传、核对与发布，让员工查到当前可用的资料。</p></div><a-button type="primary" @click="uploadStage=0;router.push('/hbos/knowledge/maintenance/upload')"><PlusOutlined/>新增资料</a-button></header>
  <a-alert v-if="error" type="error" :message="error" show-icon class="kb-alert"/><a-alert v-if="notice" type="success" :message="notice" show-icon class="kb-alert"/>
  <a-skeleton v-if="!initialized" active/>
  <a-result v-else-if="!allowed" status="403" title="当前账号没有知识维护权限" sub-title="请使用获分配维护权限的本人账号登录。"/>
  <template v-else>
   <section v-if="view==='manage'||view==='versions'" class="kb-panel hbos-glass-g1">
    <div class="kb-status-filters"><a-tag color="green">已发布 {{data?.published_documents.length||0}}</a-tag><a-button type="text" :loading="loading" @click="refresh">刷新资料</a-button></div>
    <div class="kb-list-toolbar"><a-input-search v-model:value="filter" placeholder="查找资料标题" aria-label="查找维护资料"/><a-select v-model:value="departmentFilter" :options="[{label:'全部部门',value:''},...(data?.departments.map(d=>({label:d.title,value:d.key}))||[])]" aria-label="筛选维护部门"/></div>
    <div class="kb-list-caption"><span>{{managed.length}} 份资料</span><span>{{view==='versions'?'查看当前版本和处理记录':'发布前核对质量与共享范围'}}</span></div>
    <a-skeleton v-if="loading" active :paragraph="{rows:4}"/><template v-else><article v-for="doc in visibleDocs" :key="doc.document_id" class="kb-doc-row"><div class="kb-doc-icon"><FileTextOutlined/></div><button class="kb-doc-main" @click="openDetails(doc)"><strong>{{doc.title}}</strong><p>{{doc.item?relationships[doc.item.relationship]||'资料处理记录':'当前已共享资料，查看解析质量与版本状态。'}}</p><small>{{departmentName(doc.department)}}<a-tag :color="doc.status==='已发布'?'green':'default'">{{doc.status}}</a-tag></small></button><a-button @click="openDetails(doc)">{{view==='versions'?'查看版本':'查看资料'}}</a-button></article><a-empty v-if="!managed.length" description="当前筛选没有资料。"/></template>
    <div class="kb-pagination"><a-pagination v-model:current="listPage" :total="managed.length" :page-size="4" :show-size-changer="false"/></div>
    <a-collapse ghost><a-collapse-panel key="advanced" header="高级：处理任务记录"><p class="kb-muted">处理任务记录一次上传或解析；当前版本是员工目前可用的资料修订版。</p><a-select v-model:value="selectedBatch" :disabled="busy" style="width:100%" placeholder="选择处理任务" :options="data?.batches.map(b=>({value:b.name,label:b.label}))" @change="changeBatch"/><p v-if="batch" class="kb-muted">{{batch.total}} 项 · 解析完成 {{batch.counts.parsed}} · 待核对 {{batch.total-batch.counts.quality_passed}}</p><article v-for="item in batch?.items" :key="item.version_id" class="advanced-row"><span>{{item.title}} · {{parseNames[item.parse_status]}}</span><a-button @click="detail=item;detailTitle=item.title;detailOpen=true">查看</a-button></article><a-pagination v-if="batch" v-model:current="page" :total="batch.total" :page-size="12" :show-size-changer="false" @change="refresh"/></a-collapse-panel></a-collapse>
   </section>
   <section v-if="view==='upload'" class="kb-upload-panel kb-panel hbos-glass-g1"><a-steps :current="uploadStage" :items="[{title:'选择资料'},{title:'处理进度'},{title:'核对与发布'}]"/>
    <div v-if="uploadStage===0" class="kb-upload-body"><h2>新增一份资料</h2><p>先确认资料可在公司内部共享，再选择部门与文件。</p><label for="upload-department">所属部门</label><a-select id="upload-department" v-model:value="department" :options="data?.departments.map(d=>({value:d.key,label:d.title}))" aria-label="上传资料所属部门"/><label class="kb-file-picker"><UploadOutlined/><strong>{{file?.name||'选择文件'}}</strong><span>PDF、Word、Excel、PPT、文本 · 单份最多20 MB</span><input type="file" accept=".doc,.docx,.pdf,.xlsx,.pptx,.txt,.md" aria-label="选择资料文件" @change="chooseFile"/></label><label class="version-label">版本关系<a-select show-search :filter-option="(input:string,option:any)=>String(option.label).toLowerCase().includes(input.toLowerCase())" :value="replacement?.document_id||''" :options="[{value:'',label:'新增或自动识别同内容'},...replacements.map(i=>({value:i.document_id,label:'替换：'+i.title}))]" @change="(value:string)=>replacement=replacements.find(i=>i.document_id===value)||null"/></label><a-checkbox v-model:checked="sharing">已确认本资料获准内部共享</a-checkbox><a-button type="primary" :loading="busy" :disabled="!file||!sharing" @click="upload">上传并检查重复<ArrowRightOutlined/></a-button></div>
    <div v-else class="kb-upload-body"><h2>{{uploadStage===1?'处理进度':'发布前核对'}}</h2><p>只有完成质量核对并明确发布后，员工才能检索。</p><a-alert v-if="!canParse" type="warning" message="解析服务暂不可用，已上传资料保留，可核对已有结果。"/><a-button :loading="loading" :disabled="busy" @click="refresh">刷新进度</a-button><article v-for="item in batch?.items" :key="item.version_id" class="progress-item"><strong>{{item.title}}</strong><div class="kb-progress-record"><span>重复与版本关系</span><a-tag>{{relationships[item.relationship]}}</a-tag><span>解析与索引</span><a-tag>{{parseNames[item.parse_status]}}</a-tag><span>质量核对</span><a-tag :color="item.quality_status==='Passed'?'green':'default'">{{item.relationship==='SAME_CONTENT_SKIP'?'沿用当前版本':item.quality_status==='Passed'?'已核对':'待核对'}}</a-tag><span>员工查阅</span><a-tag :color="item.publication_status==='Published'?'green':'default'">{{item.publication_status==='Published'?'已发布':item.publication_status==='Withdrawn'?'已下架':'未发布'}}</a-tag></div><a-progress v-if="item.parse_status==='parse_queued'" :percent="Math.round(item.progress*100)"/><label v-if="item.publication_status==='Withdrawn'||(item.current_version&&item.current_version!==item.version_id)" class="operation-reason">操作原因<a-input v-model:value="operationReason" :maxlength="500" placeholder="换版或恢复发布前填写原因"/></label><div class="kb-drawer-actions"><a-button v-if="['planned','uploaded','parse_failed'].includes(item.parse_status)&&item.relationship!=='SAME_CONTENT_SKIP'" type="primary" :disabled="busy||!canParse" @click="queue(item)">开始解析</a-button><a-button v-if="item.parse_status==='parsed/indexed'" :disabled="busy" @click="openQuality(item)">核对质量</a-button><a-popconfirm v-if="item.parse_status==='parsed/indexed'&&item.quality_status==='Passed'&&item.publication_status!=='Published'" title="确认本版本已核对并获准共享，发布给员工？" ok-text="确认发布" cancel-text="取消" @confirm="publish(item)"><a-button type="primary" :disabled="busy">发布资料</a-button></a-popconfirm><a-button v-if="item.relationship==='SAME_CONTENT_SKIP'" @click="router.push('/hbos/knowledge/maintenance/versions')">查看当前版本</a-button></div></article></div>
   </section>
   <section v-if="view==='feedback'" class="kb-panel hbos-glass-g1"><div class="kb-list-toolbar"><a-input-search v-model:value="feedbackQuery" placeholder="搜索反馈内容" aria-label="搜索员工反馈"/><a-select v-model:value="feedbackStatus" :options="[{label:'全部状态',value:''},{label:'待处理',value:'Pending'},{label:'处理中',value:'In Review'},{label:'已回复',value:'Resolved'}]" aria-label="筛选反馈状态"/><a-button :loading="loading" @click="refreshFeedback">刷新</a-button></div><a-skeleton v-if="loading" active/><template v-else><article v-for="item in feedbackItems" :key="item.id" class="kb-feedback-row"><MessageOutlined/><div><strong>{{item.note||item.category}}</strong><p>{{item.category}} · 员工反馈</p></div><a-tag :color="item.status==='Resolved'?'green':'default'">{{item.status==='Resolved'?'已回复':item.status==='In Review'?'处理中':'待处理'}}</a-tag><a-button @click="openFeedback(item)">处理</a-button></article><a-empty v-if="!feedbackItems.length" description="当前没有反馈。"/></template><div class="kb-pagination"><a-button :disabled="feedbackPage<=1||loading" @click="feedbackPage--">上一页</a-button><span>第 {{feedbackPage}} 页</span><a-button :disabled="!feedbackHasMore||loading" @click="feedbackPage++">下一页</a-button></div></section>
  </template>
  <p class="kb-page-footnote">发布与版本操作均保留审核记录，旧来源会重新核验。</p>
  <a-drawer :open="detailOpen" title="资料与版本" width="min(560px, 100vw)" root-class-name="kb-drawer kb-scope" @close="detailOpen=false"><h2>{{detailTitle}}</h2><a-skeleton v-if="detailLoading" active/><template v-else-if="detail"><div class="kb-version-card"><a-tag :color="detail.publication_status==='Published'?'green':'default'">{{detail.publication_status==='Published'?'当前已发布':detail.publication_status==='Withdrawn'?'已下架':'未发布'}}</a-tag><strong>{{parseNames[detail.parse_status]}} · {{detail.quality_status==='Passed'?'质量已核对':'质量待核对'}}</strong></div><p class="kb-muted">{{relationships[detail.relationship]}}。替换或下架后，旧来源与收藏需重新核验。</p><label>操作原因<a-input v-model:value="operationReason" :maxlength="500" placeholder="换版、下架或恢复前填写原因"/></label><div class="kb-drawer-actions"><a-button v-if="detail.parse_status==='parsed/indexed'" @click="openQuality(detail)">查看与核对质量</a-button><a-button v-if="['planned','uploaded','parse_failed'].includes(detail.parse_status)" :disabled="!canParse||busy" @click="queue(detail)">开始解析</a-button><a-popconfirm v-if="detail.quality_status==='Passed'&&detail.publication_status!=='Published'" title="确认核对质量并获准共享，执行发布操作？" ok-text="确认操作" cancel-text="取消" @confirm="publish(detail)"><a-button type="primary" :disabled="busy">{{detail.publication_status==='Withdrawn'?'恢复发布':'确认发布 / 换版'}}</a-button></a-popconfirm><a-popconfirm v-if="detail.publication_status==='Published'" title="下架后员工不能展开该版本来源，确认下架？" ok-text="确认下架" cancel-text="取消" @confirm="withdraw(detail)"><a-button danger :disabled="busy">下架资料</a-button></a-popconfirm><a-button @click="newRevision"><UploadOutlined/>上传新修订版</a-button></div><a-alert v-if="error" type="error" :message="error"/><a-collapse ghost><a-collapse-panel key="advanced" header="高级：处理任务记录"><p class="kb-muted">任务 {{selectedBatch}} · 版本 {{detail.version_id}}</p></a-collapse-panel></a-collapse></template><p v-else class="kb-muted">当前版本可由员工查阅。未找到本页可维护的处理记录，请选择已登记任务。</p></a-drawer>
  <a-drawer :open="qualityOpen" title="核对本版本质量" width="min(700px, 100vw)" root-class-name="kb-drawer kb-scope" :mask-closable="!busy" :closable="!busy" @close="closeQuality"><template v-if="preview"><h2>{{preview.title}}</h2><p class="kb-muted">对照获准原资料核对数字、单位、否定语和表格关系。片段顺序不能当作原页码。</p><blockquote v-for="(fragment,index) in preview.fragments" :key="index" class="quality-fragment">{{fragment.text}}<small>{{fragment.location}}</small></blockquote><a-checkbox-group v-model:value="checks" class="quality-checks"><a-checkbox value="text">正文与否定语</a-checkbox><a-checkbox value="numbers">数字、单位和条件</a-checkbox><a-checkbox value="tables">表格与条款关系</a-checkbox><a-checkbox value="identity">文件和版本身份</a-checkbox></a-checkbox-group><a-textarea v-model:value="qualityNote" :maxlength="500" :auto-size="{minRows:3,maxRows:7}" placeholder="记录核对结果与限制"/><a-button type="primary" :disabled="checks.length!==4||qualityNote.trim().length<3" :loading="busy" @click="confirmQuality">保存质量核对</a-button></template><a-alert v-else-if="error" type="error" :message="error"/><a-skeleton v-else active/></a-drawer>
  <a-drawer :open="feedbackOpen" title="处理员工反馈" width="min(520px, 100vw)" root-class-name="kb-drawer kb-scope" @close="feedbackOpen=false"><template v-if="selectedFeedback"><h2>{{selectedFeedback.category}}</h2><p>{{selectedFeedback.note}}</p><p class="kb-muted">回复只向提交人和维护人展示。</p><a-textarea v-model:value="reply" :rows="5" :maxlength="500" placeholder="填写处理结果或回复…"/><div class="kb-drawer-actions"><a-button :disabled="busy" @click="reviewFeedback('In Review')">标记处理中</a-button><a-button type="primary" :disabled="busy||!reply.trim()" :loading="busy" @click="reviewFeedback('Resolved')">回复并完成</a-button></div><a-alert v-if="error" type="error" :message="error"/></template></a-drawer>
 </div>
</template>
<style scoped>
.maintenance-page{min-width:0}.operation-reason{display:grid;gap:8px;margin:20px 0;font-size:14px}.version-label{display:grid;gap:8px;margin:20px 0}.advanced-row{display:flex;justify-content:space-between;gap:16px;padding:16px 0;border-bottom:1px solid var(--hbos-border-default);font-size:14px}.advanced-row>span{min-width:0;overflow-wrap:anywhere}.kb-progress-record{display:grid;grid-template-columns:1fr auto;gap:16px;padding:24px;background:#f4f8fa;border-radius:16px;margin-top:24px;font-size:14px}.progress-item{margin:24px 0}.quality-fragment{border-left:3px solid var(--hbos-brand-aqua);padding:16px;margin:16px 0;white-space:pre-wrap;overflow-wrap:anywhere;font-size:16px;line-height:28px;background:#f7f9fc}.quality-fragment small{display:block;color:var(--hbos-text-muted);font-size:12px;margin-top:8px}.quality-checks{display:flex;flex-direction:column;gap:12px;margin:24px 0}.quality-checks+.ant-input{margin-bottom:24px}.kb-upload-body>.ant-checkbox-wrapper{margin-top:20px}.kb-upload-body>label{font-size:14px}.kb-file-picker:focus-within{outline:2px solid var(--hbos-brand-aqua);outline-offset:3px}.kb-drawer label .ant-input{margin-top:12px}.kb-list-toolbar h2{font-size:20px;line-height:28px;margin:0}
@media(max-width:600px){.kb-progress-record{padding:16px;gap:12px}.advanced-row{flex-wrap:wrap}}
</style>
