import { mount, flushPromises } from '@vue/test-utils'
import { defineComponent } from 'vue'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import Connections from '@/components/knowledge/KnowledgeConnections.vue'
const api=vi.hoisted(()=>({get:vi.fn(),create:vi.fn(),revoke:vi.fn()}))
vi.mock('@/services/p1Api',async original=>({...await original<typeof import('@/services/p1Api')>(),getKnowledgeConnections:api.get,createKnowledgeConnection:api.create,revokeKnowledgeConnection:api.revoke}))
const Drawer=defineComponent({props:['open'],emits:['close'],template:'<section v-if="open"><slot/><button data-close @click="$emit(\'close\')">close</button></section>'})
const Button=defineComponent({props:['disabled','htmlType'],template:'<button :disabled="disabled" :type="htmlType||\'button\'"><slot/></button>'})
const stubs={'a-drawer':Drawer,'a-button':Button,'a-alert':{props:['message','description'],template:'<p>{{message}} {{description}}</p>'},'a-skeleton':true,'a-empty':true}
const info={items:[],tools:['list_knowledge_spaces','search_knowledge','get_evidence','ask_knowledge'],endpoint:'http://local.test/mcp',deployment:'LOCAL_UAT',query_blocked:true,client_versions:{OpenClaw:'SYNTHETIC',Hermes:'SYNTHETIC'},client_verification:{OpenClaw:'VERIFIED_TOOLS_ONLY_QUERY_BLOCKED',Hermes:'VERIFIED_QUERY_AND_SOURCE_BEFORE_BUDGET_STOP'}}
function deferred(){let resolve!:(value:any)=>void,reject!:(e:Error)=>void;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}}
async function opened(){const w=mount(Connections,{props:{open:false,subject:'A'},global:{stubs}});await w.setProps({open:true});await flushPromises();return w}
beforeEach(()=>{vi.clearAllMocks();api.get.mockResolvedValue(info);api.create.mockResolvedValue({id:'CONNECTION_SYNTHETIC',token:'SYNTHETIC_PRIVATE_TOKEN',expires_at:'2026-10-12'});api.revoke.mockResolvedValue({revoked:true})})
describe('personal connection privacy during late responses — synthetic, no native credentials',()=>{
 it('never renders credentials returned after the drawer closes',async()=>{const pending=deferred();api.create.mockReturnValue(pending.promise);const w=await opened();await w.get('form').trigger('submit');await w.get('[data-close]').trigger('click');await w.setProps({open:false});pending.resolve({token:'SYNTHETIC_PRIVATE_TOKEN'});await flushPromises();await w.setProps({open:true});await flushPromises();expect(w.find('#mcp-template').exists()).toBe(false);expect(w.text()).not.toContain('SYNTHETIC_PRIVATE_TOKEN');w.unmount()})
 it('drops the former subject credential and lets the new subject create a connection',async()=>{const pending=deferred();api.create.mockReturnValueOnce(pending.promise);const w=await opened();await w.get('form').trigger('submit');await w.setProps({subject:'B'});await flushPromises();expect(w.get('#mcp-label').attributes('disabled')).toBeUndefined();pending.resolve({token:'FORMER_SUBJECT_TOKEN'});await flushPromises();expect(w.find('#mcp-template').exists()).toBe(false);await w.get('form').trigger('submit');await flushPromises();expect(w.get('textarea').element).toHaveProperty('value',expect.stringContaining('SYNTHETIC_PRIVATE_TOKEN'));w.unmount()})
 it('an older failed refresh cannot replace a newer successful refresh',async()=>{const pending=deferred();api.get.mockReturnValueOnce(pending.promise);const w=await opened();await w.setProps({subject:'B'});await flushPromises();pending.reject(new Error('OLD_PRIVATE_FAILURE'));await flushPromises();expect(w.text()).not.toContain('连接操作暂时不可用');expect(w.text()).toContain('OpenClaw 的认证');w.unmount()})
 it('renders tested transport JSON and hides it when changing client',async()=>{const w=await opened();await w.get('form').trigger('submit');await flushPromises();const value=JSON.parse((w.get('textarea').element as HTMLTextAreaElement).value);expect(value).toEqual({transport:'streamable-http',url:info.endpoint,headers:{Authorization:'Bearer SYNTHETIC_PRIVATE_TOKEN'}});await w.get('select').setValue('Hermes');expect(w.find('textarea').exists()).toBe(false);expect(w.text()).toContain('Hermes 已装版本');w.unmount()})
})
